import { AlignmentType, BorderStyle, Document, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import type { PrebudgetDocument } from "./createDocument";
export { exportPrebudgetHwpx } from "./exportHwpx";

const safeName = (title: string) => `${title.replace(/\s*성립전예산\s*$/, "").replace(/[\\/:*?"<>|]/g, "_").trim() || "성립전예산"}_성립전예산`;
export const prebudgetFilename = (title: string, extension: string) => `${safeName(title)}.${extension}`;
export function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
const wordCell = (text: string, bold = false) => new TableCell({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text, bold, size: 16 })] })] });
const wordRow = (values: string[], bold = false) => new TableRow({ children: values.map((value) => wordCell(value, bold)) });
export async function exportPrebudgetWord(data: PrebudgetDocument) { const border = { style: BorderStyle.SINGLE, size: 4 }; const table = new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [wordRow(data.budgetTable.headers, true), ...data.budgetTable.rows.map((values) => wordRow(values)), wordRow(["합계", "", "", "", "", "", data.budgetTable.total], true)], borders: { top: border, bottom: border, left: border, right: border, insideHorizontal: border, insideVertical: border } }); const doc = new Document({ sections: [{ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: data.title, bold: true, size: 34 })], spacing: { after: 500 } }), ...data.bodyLines.map((text) => new Paragraph(text)), table] }] }); return { blob: await Packer.toBlob(doc), filename: prebudgetFilename(data.title, "docx") }; }
export async function exportPrebudgetPdf(element: HTMLElement, title: string) { const canvas = await html2canvas(element, { scale: 2, backgroundColor: "#fff", useCORS: true }); const pdf = new jsPDF({ unit: "mm", format: "a4" }); const pageHeight = 277; const imageHeight = canvas.height * 190 / canvas.width; const image = canvas.toDataURL("image/jpeg", .94); let remainingHeight = imageHeight; let position = 10; pdf.addImage(image, "JPEG", 10, position, 190, imageHeight); remainingHeight -= pageHeight; while (remainingHeight > 0) { position -= pageHeight; pdf.addPage(); pdf.addImage(image, "JPEG", 10, position, 190, imageHeight); remainingHeight -= pageHeight; } return { blob: pdf.output("blob"), filename: prebudgetFilename(title, "pdf") }; }
