import { AlignmentType, BorderStyle, Document, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import type { PrebudgetDocument } from "./createDocument";

const safeName = (title: string) => `${title.replace(/\s*성립전예산\s*$/, "").replace(/[\\/:*?"<>|]/g, "_").trim() || "성립전예산"}_성립전예산`;
export function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
const cell = (text: string, bold = false) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text, bold })] })] });
export async function exportPrebudgetWord(data: PrebudgetDocument) { const rows = [new TableRow({ children: ["단위사업", "세부사업", "세부항목", "원가통계비목", "산출내역", "금액"].map((v) => cell(v, true)) }), ...data.items.map((i) => new TableRow({ children: [i.unitBusiness!, i.business!, i.detail!, i.category!, i.description!, `${i.amount.toLocaleString()}원`].map((v) => cell(v)) }))]; const doc = new Document({ sections: [{ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: data.title, bold: true, size: 34 })], spacing: { after: 500 } }), ...data.copyText.split("\n").slice(2, 9).map((text) => new Paragraph(text)), new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows, borders: Object.fromEntries(["top", "bottom", "left", "right", "insideHorizontal", "insideVertical"].map((key) => [key, { style: BorderStyle.SINGLE, size: 4 }])) }), new Paragraph({ text: "붙임  성립전예산 요구내역 1부.  끝.", spacing: { before: 300 } })] }] }); return { blob: await Packer.toBlob(doc), filename: `${safeName(data.title)}.docx` }; }
export async function exportPrebudgetPdf(element: HTMLElement, title: string) { const canvas = await html2canvas(element, { scale: 2, backgroundColor: "#fff", useCORS: true }); const pdf = new jsPDF({ unit: "mm", format: "a4" }); const height = Math.min(277, canvas.height * 190 / canvas.width); pdf.addImage(canvas.toDataURL("image/jpeg", .94), "JPEG", 10, 10, 190, height); return { blob: pdf.output("blob"), filename: `${safeName(title)}.pdf` }; }
export function exportPrebudgetExcel(data: PrebudgetDocument) { const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([[data.title], [], ["학교명", data.schoolName], ["회계연도", data.fiscalYear], ["재원구분", data.source], ["부서명", data.department], ["요구자", data.requester], ["관련 공문", data.officialDocument], ["예산요구 총액", data.total], [], ...data.copyText.split("\n").map((line) => [line])]), "기안문"); XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([["단위사업", "세부사업", "세부항목", "원가통계비목", "산출내역", "단가", "수량", "횟수", "금액"], ...data.items.map((i) => [i.unitBusiness, i.business, i.detail, i.category, i.description, i.unitPrice, i.quantity, i.count, i.amount]), ["합계", "", "", "", "", "", "", "", data.total]]), "예산요구내역"); return { blob: new Blob([XLSX.write(workbook, { bookType: "xlsx", type: "array" })]), filename: `${safeName(data.title)}.xlsx` }; }
